### ISSUE TITLE
Katy Comments on NO report

### ISSUE THREAD

**Issue by katyhuff** [arfc/ddca_numerical_exp#16]
See scribbles in this pdf for to-do recommendations:
[no_numerical_exp_report.pdf](https://github.com/arfc/ddca_numerical_exp/files/2290498/no_numerical_exp_report.pdf)

This issue can be closed when a PR handling these suggestions has been merged.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/ddca_numerical_exp/pull/17.
