### ISSUE TITLE
Summer Transition Report

### ISSUE THREAD

**Issue by gwenchee** [arfc/ddca_numerical_exp#24]
This issue can be closed after @sonatav2 and @robfairh read the summer transition report. In the report, I candidly added some comments and recommendations for setting up the large transition scenario. In the conclusions section, I made a recommendation for what @sonatav2 could work on while @robfairh is in Sweden taking the nuclear waste course. Feel free to reach out to me if y'all need any help :) 

[report.pdf](https://github.com/arfc/ddca_numerical_exp/files/3213135/report.pdf)

Also, could someone merge https://github.com/arfc/ddca_numerical_exp/pull/22 if you are satisfied with the report.

**Comment by sonatav2** [comment]
Read - thanks for putting this together! :)

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/ddca_numerical_exp/pull/22
