### ISSUE TITLE
Update of the report

### ISSUE THREAD

**Issue by robfairh** [arfc/ddca_numerical_exp#26]
The report should add the demonstrations of d3ploy capabilities using the transition scenarios.

Addressed by #25 

The .pdf can we found here:
[report.pdf](https://github.com/arfc/ddca_numerical_exp/files/3373519/report.pdf)

This issue can be closed when @robfairh updates the report.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/ddca_numerical_exp/pull/25
