### ISSUE TITLE
Review of Summer Report 

### ISSUE THREAD

**Issue by gwenchee** [arfc/ddca_numerical_exp#30]
This issue can be closed after @katyhuff reviews the summer transition scenarios report.
[report.pdf](https://github.com/arfc/ddca_numerical_exp/files/3422360/report.pdf)

**Comment by katyhuff** [comment]
- [ ] @robfairh The current draft of the report is missing a coversheet (see issue #28 ) 
- [ ] @robfairh and @gwenchee , if you have not done so yet, please conduct a review using the writing checklist. If this has been completed, please close issue #27 . 

When these two issues are handled, I'll take a look at the report.

**Comment by gwenchee** [comment]
I have reviewed the writing checklist, you can close #27 if you also have @robfairh

**Comment by robfairh** [comment]
@katyhuff I have uploaded the updated report (#31).

**Comment by katyhuff** [comment]
Closed. As mentioned in #31 , I'll make edits directly to this version if needed.
