### ISSUE TITLE
What's the deal with the directory called "final"?

### ISSUE THREAD

**Issue by katyhuff** [arfc/ddca_numerical_exp#45]
There is both a directory called "final" and one called "final-report." 

(Neither, in fact, is the project's final report, which is distinct from the report satifying the final milestone and has not yet been written.)

I have made a PR that changes the name of "final-report" to uiuc-arfc-2019-05.

But -- I can't figure out the purpose or proper fate of the directory called "final". This issue can be closed when someone:

- explains what the deal is.
- and/or a pull request is merged which changes the name of that directory or deletes it entirely.

**Comment by gwenchee** [comment]
I created the "final" directory in PR #19 back when I thought that each of us was going to contribute a section of the "final-report" (issue #20). I think there was miscommunication between @robfairh and me, and another folder was created. I'll make a PR to delete the "final" directory.

**Comment by robfairh** [comment]
Closed with #46
